# Generated by Django 5.1.1 on 2024-10-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_article_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="slug",
            field=models.SlugField(blank=True, default=" ", max_length=255),
        ),
    ]
